experiment_name: "Exp2_MP_Tr_Dice"
model:
  downsample_mode: "mp"
  upsample_mode: "tr"
training:
  loss: "dice"
  learning_rate: 0.001
  batch_size: 32
  epochs: 15
data:
  path: "../data/raw/Oxford-IIT-PetDataset/"
  img_size: [128, 128]